import { Car } from './car';

export const MOCK_CARS: Car[] = [{
  carId: 1,
  make: 'Kia',
  model: 'Soul',
  year: 2011,
  value: 12000,
  mileage: 70000,
  fuel: 'gasoline',
  exteriorColor: 'Silver',
  interiorColor: 'Black',
  transmission: 'automatic',
  engine: '4-Cylinder',
  driveType: '2 wheel drive - front',
  description: 'Beautiful hamster car',
  status: 1,
  ownerId: 1,
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/Kia_Soul.jpeg'
}, {
  carId: 2,
  make: 'Ford',
  model: 'Mustang',
  year: 2017,
  value: 30000,
  mileage: 10000,
  fuel: 'gasoline',
  exteriorColor: 'Red',
  interiorColor: 'Charcoal',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: '2 wheel drive - rear',
  description: 'American Muscle',
  status: 1,
  ownerId: 1,
  photoLink: null
}, {
  carId: 3,
  make: 'Chevy',
  model: 'Silverado',
  year: 2015,
  value: 22000,
  mileage: 35000,
  fuel: 'gasoline',
  exteriorColor: 'Black',
  interiorColor: 'Beige Leather',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: '4 wheel drive',
  description: 'Made to haul',
  status: 1,
  ownerId: 1,
  photoLink: null
}, {
  carId: 4,
  make: 'Chevy',
  model: 'Camaro',
  year: 2010,
  value: 18000,
  mileage: 42350,
  fuel: 'gasoline',
  exteriorColor: 'Blue',
  interiorColor: 'White',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: '2 wheel drive - rear',
  description: 'Dope Camaro goes woo woo',
  status: 1,
  ownerId: 2,
  photoLink: null
}, {
  carId: 1,
  make: 'Kia',
  model: 'Soul',
  year: 2011,
  value: 12000,
  mileage: 70000,
  fuel: 'gasoline',
  exteriorColor: 'Silver',
  interiorColor: 'Black',
  transmission: 'automatic',
  engine: '4-Cylinder',
  driveType: '2 wheel drive - front',
  description: 'Beautiful hamster car',
  status: 1,
  ownerId: 1,
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/Kia_Soul.jpeg'
}, {
  carId: 3,
  make: 'Chevy',
  model: 'Silverado',
  year: 2015,
  value: 22000,
  mileage: 35000,
  fuel: 'gasoline',
  exteriorColor: 'Black',
  interiorColor: 'Beige Leather',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: '4 wheel drive',
  description: 'Made to haul',
  status: 1,
  ownerId: 1,
  photoLink: null
}];
