import { USERS } from './mock-users';
import { Car } from './models/car';

export const MOCK_CARS: Car[] = [{
  carId: 1,
  make: 'Bugatti',
  model: 'Divo',
  year: 2019,
  value: 249999,
  mileage: 14000,
  fuel: 'gasoline',
  exteriorColor: 'Charcoal w/Blue Highlights',
  interiorColor: 'Black Leather',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: '4 wheel drive',
  description: 'The road destroyer',
  saleStatus: 'FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/bugatti_divo.jpg'
}, {
  carId: 2,
  make: 'Bugatti',
  model: 'Chiron',
  year: 2018,
  value: 215000,
  mileage: 10000,
  fuel: 'gasoline',
  exteriorColor: 'Black w/Orange Stripes',
  interiorColor: 'Black',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'Racing Stripes for the racing types',
  saleStatus: 'FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/bugatti_chiron.jpg'
}, {
  carId: 3,
  make: 'Bugatti',
  model: 'Centodieci',
  year: 2020,
  value: 749999,
  mileage: 35000,
  fuel: 'gasoline',
  exteriorColor: 'White with black',
  interiorColor: 'Silver',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: '4 wheel drive',
  description: 'White out for a night out',
  saleStatus: 'FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/bugatti_centodieci.jpg'
}, {
  carId: 4,
  make: 'Aston Martin',
  model: 'Vanquish',
  year: 2016,
  value: 293650,
  mileage: 22500,
  fuel: 'gasoline',
  exteriorColor: 'Grey',
  interiorColor: 'Cream',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'Vanquishing the anguishing',
  saleStatus: 'FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/Aston_Martin_Vanquish.jpg'
}, {
  carId: 5,
  make: 'Aston Martin',
  model: 'Valhalla',
  year: 2017,
  value: 1299999,
  mileage: 4500,
  fuel: 'gasoline',
  exteriorColor: 'White',
  interiorColor: 'Cream',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'Conceptual car raising the literal bar',
  saleStatus: 'FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/aston_martin_valhalla.jpeg'
}, {
  carId: 6,
  make: 'Bugatti',
  model: 'Veyron',
  year: 2019,
  value: 129999,
  mileage: 6500,
  fuel: 'gasoline',
  exteriorColor: 'Black w/Blue highlights',
  interiorColor: 'Charcoal',
  transmission: 'automatic',
  engine: '6-Cylinder',
  driveType: '4 wheel drive',
  description: 'This thing goes fast',
  saleStatus: 'FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/bugatti_veyron_vitesse.jpg'
}, {
  carId: 7,
  make: 'W Motors',
  model: 'Lykan',
  year: 2019,
  value: 435999,
  mileage: 7200,
  fuel: 'gasoline',
  exteriorColor: 'Red-Orange',
  interiorColor: 'Black',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'Get a ticket in the HyperSport, head to HyperCourt',
  saleStatus: 'FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/w_motors_lykan.jpg'
}, {
  carId: 8,
  make: 'W Motors',
  model: 'Fenryr',
  year: 2019,
  value: 438750,
  mileage: 2150,
  fuel: 'gasoline',
  exteriorColor: 'Blue',
  interiorColor: 'Black',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The ride home in the SuperSport is SuperShort',
  saleStatus: 'FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/w_motors_fenyr.jpg'
}, {
  carId: 9,
  make: 'Lamborghini',
  model: 'Huracan',
  year: 2018,
  value: 349999,
  mileage: 16500,
  fuel: 'gasoline',
  exteriorColor: 'All Black',
  interiorColor: 'Black Leather',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The Huracan for the amurricahn',
  saleStatus: 'FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/lamborghini_huracan.jpg'
}, {
  carId: 10,
  make: 'Lamborghini',
  model: 'Sian',
  year: 2019,
  value: 435650,
  mileage: 9250,
  fuel: 'gasoline',
  exteriorColor: 'Gold',
  interiorColor: 'Cream',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'This word is hard to rhyme.',
  saleStatus: 'FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/lamborghini_sian.jpg'
}, {
  carId: 11,
  make: 'Lamborghini',
  model: 'Centenario',
  year: 2019,
  value: 525000,
  mileage: 1500,
  fuel: 'gasoline',
  exteriorColor: 'Black w/Gold highlights',
  interiorColor: 'Black',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The Centenario will take you far-io',
  saleStatus: 'FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/lamborghini_centenario.jpg'
}, {
  carId: 12,
  make: 'Lamborghini',
  model: 'Aventador',
  year: 2018,
  value: 425000,
  mileage: 2349,
  fuel: 'gasoline',
  exteriorColor: 'White Sketch Design',
  interiorColor: 'Black',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The Aventador will cost you four... arms & legs',
  saleStatus: 'NOT_FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/lamborghini_aventador.jpg'
}, {
  carId: 13,
  make: 'Koenigsegg',
  model: 'Trevita',
  year: 2010,
  value: 1125000,
  mileage: 4500,
  fuel: 'gasoline',
  exteriorColor: 'Silver and Black',
  interiorColor: 'Beige',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The Trevita is tres sweeta',
  saleStatus: 'NOT_FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/koenigsegg_trevita.jpg'
}, {
  carId: 14,
  make: 'Koenigsegg',
  model: 'Regera',
  year: 2019,
  value: 1350000,
  mileage: 1250,
  fuel: 'gasoline',
  exteriorColor: 'Red',
  interiorColor: 'Black',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'Long Regera don\'t careuh',
  saleStatus: 'NOT_FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/koenigsegg_regera.jpg'
}, {
  carId: 15,
  make: 'Koenigsegg',
  model: 'Jesko',
  year: 2019,
  value: 755999,
  mileage: 1250,
  fuel: 'gasoline',
  exteriorColor: 'White w/Lime Highlights',
  interiorColor: 'Cream',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'Buy now to get the Jesko for lessko!',
  saleStatus: 'NOT_FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/koenigsegg_jesko.jpg'
}, {
  carId: 16,
  make: 'Aston Martin',
  model: 'One-77',
  year: 2019,
  value: 1950000,
  mileage: 13500,
  fuel: 'gasoline',
  exteriorColor: 'Silver/Grey',
  interiorColor: 'Black & Cream',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The One-77 is like driving in heaven',
  saleStatus: 'NOT_FOR_SALE',
  owner: USERS[0],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/aston_martin_one77.jpg'
}, {
  carId: 17,
  make: 'Koenigsegg',
  model: 'Agera',
  year: 2019,
  value: 849500,
  mileage: 11250,
  fuel: 'gasoline',
  exteriorColor: 'Silver w/Black Stripes',
  interiorColor: 'Charcoal',
  transmission: 'manual',
  engine: '6-Cylinder',
  driveType: 'All Wheel Drive',
  description: 'The Agera will scare-ya!',
  saleStatus: 'NOT_FOR_SALE',
  owner: USERS[1],
  photoLink: 'https://angular-car-sales.s3.amazonaws.com/Car+Photos/koenigsegg_agera.jpg'
}];
